config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "welcome/index"
  root to: "welcome#index"

  resources :organisations
  resources :clients do
    resources :contacts
  end
  resources :platforms
  resources :positions
  resources :targets
  resources :ads

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.superadmin_role? || user.manager_role?
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/ad.rb
class Ad < ApplicationRecord
  belongs_to :position
  belongs_to :client
  belongs_to :user

  def self.in_publication_range(start_date, end_date)
    where("rundate >= ? AND rundate <= ?", start_date, end_date)
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :organisation
  belongs_to :user

  has_many :contacts
  has_many :ads

end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :client
end

app/models/organisation.rb
class Organisation < ApplicationRecord
  has_many :users
  has_many :clients
  has_many :platforms
end

app/models/platform.rb
class Platform < ApplicationRecord
  belongs_to :organisation
  has_many :positions
  has_many :targets
end

app/models/position.rb
class Position < ApplicationRecord
  belongs_to :platform
  has_many :ads
end

app/models/target.rb
class Target < ApplicationRecord
  belongs_to :platform
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :organisation
  has_many :clients
  has_many :ads
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def index
    if can? :manage, User
      @ads = Ad.all
    else
      @ads = current_user.ads
    end
    @ad = Ad.new
    @clients = Client.all
    @platforms = Platform.all
    @positions = Position.all
  end

  def create
    @ad = Ad.new(ad_params)

    respond_to do |format|
      if @ad.save
        format.html { redirect_to @ad, notice: 'Ad was successfully created.' }
        format.js
        format.json { render json: @ad, status: :created, location: @ad }
      else
        format.html { render action: "error" }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def ad_params
      params.require(:ad).permit(:width, :height, :status, :price, :rundate, :client_id, :position_id, :user_id, :updated_by)
    end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    @clients = Client.all
  end

  def show
    @client = Client.find(params[:id])
    @contacts = Contact.where(client_id: @client.id)
    @ads = @client.ads
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.create(client_params)

    if @client.save
      flash.notice = "Client saved"
      redirect_to clients_path
    else
      flash.now[:error] = "Something went wrong: #{@client.errors.full_messages}"
      render_action :new
    end
  end

  def edit

  end

  def delete

  end

end

private
  def client_params
    params.require(:client).permit(:name, :address, :phone, :website, :organisation_id, :user_id)
  end

app/controllers/platforms_controller.rb
class PlatformsController < ApplicationController
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def index
    @platforms = Platform.all
  end

  def show
    @platform = Platform.find(params[:id])
    @positions = @platform.positions
    @clients = Client.all
    @ad = Ad.new
  end

  def new
    @platform = Platform.new
  end

  def create
    @platform = Platform.create(platform_params)

    if @platform.save
      flash.notice = "Platform, #{@platform.name} created"
      redirect_to platforms_path
    else
      render :new
    end
  end

  def edit
    @platform = Platform.find(params[:id])
  end

  def update
    @platform = Platform.find(params[:id])

    if @platform.update(platform_params)
      flash.notice = "Platform updated"
      redirect_to platforms_path
    else
      flash.error = "Uh oh"
      render :edit
    end
  end

  def get_positions
    @positions
  end

  private
    def platform_params
      params.require(:platform).permit(:name, :organisation_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/ads_helper.rb
module AdsHelper

  def publication_end_range(platform_id)
    p = Platform.find(platform_id)
    if p.daily
      return Date.today + 1
    elsif p.weekly
      return Date.today + 1.week
    elsif p.monthly
      return Date.today + 1.month
    end
  end

  def value(collection)
    v = 0
    collection.each do |c|
      v += c.price
    end
    return v
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def get_username_by_id(id)
    u = User.find(id)
    return u.first_name
  end

  def sidebar_class(page)
    if current_page?(page)
      return "nav-link py-3 border-bottom active"
    else
      return "nav-link py-3 border-bottom"
    end
  end

end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/organisations_helper.rb
module OrganisationsHelper
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/platforms/_ad.html.erb
<tr>
  <td><%= ad.client.name.truncate(30) %></td>
  <td><%= ad.width.to_s + " x " + ad.height.to_s %></td>
  <td><%= ad.position.name %></td>
  <td><%= ad.position.platform.name %></td>
  <td><%= ad.rundate.strftime("%a, %d %b") %></td>
  <td><%= ad.status %></td>
  <td>$<%= ad.price %></td>
  <% if can? :manage, User %>
    <td><%= ad.user.first_name %></td>
  <% end %>

  <td><%= ad.created_at.strftime("%d/%m/%y") %></td>
  <td><%= time_ago_in_words(ad.updated_at) %> ago by <%= get_username_by_id(ad.updated_by) %></td>
</tr>

app/views/platforms/_booking.html.erb
<div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasAd" aria-labelledby="Positions">
  <div class="offcanvas-header">
    <h3 class="offcanvas-title" id="offcanvasCreateAd">Create Ad</h3>
    <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
    <%= form_with( model: @ad, id: "new-ad", local: false ) do |form| %>
      <div class="mb-3">
        <%= form.label :client, class: "form-label" %>
        <%= form.collection_select(:client_id, clients, :id, :name, {}, {class: "form-select form-control"}) %>
      </div>
      <div class="mb-3">
        <%= form.label :position, class: "form-label" %>
        <%= form.collection_select(:position_id, positions, :id, :name, {}, {class: "form-select position-select form-control"}) %>
      </div>
      <div class="mb-3">
        <%= form.label :width, class: "form-label" %>
        <%= form.number_field :width, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= form.label :height, class: "form-label" %>
        <%= form.number_field :height, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= form.label :status, class: "form-label" %>
        <%= form.text_field :status, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= form.label :price, class: "form-label" %>
        <%= form.number_field :price, step: 0.01, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= form.label :rundate, class: "form-label" %>
        <%= form.date_field :rundate %>
      </div>
      <div class="mb-3">
      <%= form.hidden_field :user_id, value: current_user.id %>
      <%= form.hidden_field :updated_by, value: current_user.id %>
      <%= form.submit :Submit, class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/platforms/_form.html.erb
<%= form_with model: @platform do |form| %>
  <%= form.label :name %><br />
  <%= form.text_field :name %>
  <%= form.hidden_field :organisation_id, value: current_user.organisation_id %>
  <%= form.submit %>
<% end %>

app/views/platforms/create.js.erb
var ads = document.querySelector("#ad-table");
ads.insertAdjacentHTML("afterbegin", "<%= j render(@ad) %>");
toastr.success('Ad created successfully', 'Success')

app/views/platforms/edit.html.erb
<section class="py-5 container">
  <div class="card">
    <div class="card-header">
      Edit Platform
    </div>
    <div class="card-body">
      <%= render "form" %>
    </div>
</section>

app/views/platforms/index.html.erb
<section class="py-5 container">

  <div class="card">
    <div class="card-header">
      Platforms
    </div>
    <div class="card-body">
      <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <%= link_to('New Platform', new_platform_url, class: "btn btn-primary") %>
        <%= link_to('New Position', new_position_url, class: "btn btn-primary") %>
      </div>

      <hr />
      <table class="table table-hover">
        <thead>
          <tr>
            <th>ID#</th>
            <th>Platform</th>
            <th>Controls</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @platforms.each do |p| %>
            <tr>
              <td><%= p.id %></td>
              <td><%= link_to(p.name, platform_path(p.id)) %></td>
              <td>
                <button class="btn btn-primary" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasPosition<%= p.id %>" aria-controls="offcanvasExample">
                  Show positions
                </button>
              </td>
              <td>
                <div class="dropdown">
                  <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                    Actions
                  </button>
                  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                    <li><%= link_to('Edit', edit_platform_url(p.id), class: 'dropdown-item') %></li>
                    <!-- <li><%= link_to('Delete', platform_path(p.id), method: :delete, data: {confirm: 'Are you sure?'}, class: 'dropdown-item') %></li> -->
                  </ul>
                </div>
              </td>
            </tr>

            <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasPosition<%= p.id %>" aria-labelledby="Positions">
              <div class="offcanvas-header">
                <h3 class="offcanvas-title" id="offcanvasExampleLabel"><%= p.name %></h3>
                <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
              </div>
              <div class="offcanvas-body">
                <h5>Positions</h5>
                <ul>
                  <% p.positions.each do |q| %>
                    <li><%= q.name %></li>
                  <% end %>
                </ul>
              </div>
            </div>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

</section>

app/views/platforms/new.html.erb
<section class="py-5 container">
  <div class="card">
    <div class="card-header">
      Create Platform
    </div>
    <div class="card-body">
      <%= render "form" %>
    </div>
</section>

app/views/platforms/show.html.erb
<section class="py-5 container">
  <div class="card">
    <div class="card-header">
      <%= @platform.name %>
    </div>
    <div class="card-body">

      <div class="btn-toolbar d-grid gap-2 d-md-flex justify-content-between">
        <div class="btn-group">
          <a href="#" class="btn btn-primary active">Next</a>
        </div>

        <div>
          <%= "Showing ads #{Date.today} - #{publication_end_range(@platform.id)}" %>
        </div>

        <button class="btn btn-primary" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasAd" type="submit">Create booking</button>
      </div>

      <hr />
      <div class="accordion" id="positionAccordion">
        <% @positions.each do |p| %>
          <% if p.ads.in_publication_range(Date.today, publication_end_range(p.platform.id)).count > 0 %>
            <div class="accordion-item">
              <h2 class="accordion-header" id="heading-<%= p.id %>">
                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse<%= p.id %>" aria-controls="collapse<%= p.id %>">
                  <%= p.name %>
                </button>
              </h2>
              <div id="collapse<%= p.id %>" class="accordion-collapse collapse" aria-labelledby="heading-<%= p.id %>">
                <div class="accordion-body">

                  <%= render partial: "shared/ad_table_container", locals: {ads: p.ads.in_publication_range(Date.today, publication_end_range(p.platform.id))} %>

                </div>
              </div>
            </div>
          <% end %>
        <% end %>

        </div> <!-- End accordion -->

        <%= render partial: "booking", locals: {positions: @positions, clients: @clients} %>

      </div><!-- End card body -->
    </div>
</section>