config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "welcome/index"
  root to: "welcome#index"

  resources :organisations
  resources :clients do
    resources :contacts
  end
  resources :platforms
  resources :positions
  resources :targets
  resources :ads

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.superadmin_role? || user.manager_role?
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/ad.rb
class Ad < ApplicationRecord
  belongs_to :position
  belongs_to :client
  belongs_to :user

  def self.in_publication_range(start_date, end_date)
    where("rundate >= ? AND rundate <= ?", start_date, end_date)
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :organisation
  belongs_to :user

  has_many :contacts
  has_many :ads

end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :client
end

app/models/organisation.rb
class Organisation < ApplicationRecord
  has_many :users
  has_many :clients
  has_many :platforms
end

app/models/platform.rb
class Platform < ApplicationRecord
  belongs_to :organisation
  has_many :positions
  has_many :targets
end

app/models/position.rb
class Position < ApplicationRecord
  belongs_to :platform
  has_many :ads
end

app/models/target.rb
class Target < ApplicationRecord
  belongs_to :platform
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :organisation
  has_many :clients
  has_many :ads
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def index
    if can? :manage, User
      @ads = Ad.all
    else
      @ads = current_user.ads
    end
    @ad = Ad.new
    @clients = Client.all
    @platforms = Platform.all
    @positions = Position.all
  end

  def create
    @ad = Ad.new(ad_params)

    respond_to do |format|
      if @ad.save
        format.html { redirect_to @ad, notice: 'Ad was successfully created.' }
        format.js
        format.json { render json: @ad, status: :created, location: @ad }
      else
        format.html { render action: "error" }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def ad_params
      params.require(:ad).permit(:width, :height, :status, :price, :rundate, :client_id, :position_id, :user_id, :updated_by)
    end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    @clients = Client.all
  end

  def show
    @client = Client.find(params[:id])
    @contacts = Contact.where(client_id: @client.id)
    @ads = @client.ads
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.create(client_params)

    if @client.save
      flash.notice = "Client saved"
      redirect_to clients_path
    else
      flash.now[:error] = "Something went wrong: #{@client.errors.full_messages}"
      render_action :new
    end
  end

  def edit

  end

  def delete

  end

end

private
  def client_params
    params.require(:client).permit(:name, :address, :phone, :website, :organisation_id, :user_id)
  end

app/helpers/ads_helper.rb
module AdsHelper

  def publication_end_range(platform_id)
    p = Platform.find(platform_id)
    if p.daily
      return Date.today + 1
    elsif p.weekly
      return Date.today + 1.week
    elsif p.monthly
      return Date.today + 1.month
    end
  end

  def value(collection)
    v = 0
    collection.each do |c|
      v += c.price
    end
    return v
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def get_username_by_id(id)
    u = User.find(id)
    return u.first_name
  end

  def sidebar_class(page)
    if current_page?(page)
      return "nav-link py-3 border-bottom active"
    else
      return "nav-link py-3 border-bottom"
    end
  end

end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/organisations_helper.rb
module OrganisationsHelper
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Adbot</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://cdn.jsdelivr.net/npm/simple-datatables@latest' %>

  </head>

  <body>

    <main>
      <%= render "shared/sidebar" %>
      <%= render "shared/toastr-notifications" %>
      <div class="container overflow-auto" style="max-width:94.3%">
        <%= yield %>
      </div>

    </main>

    <script>
      dataTable = new simpleDatatables.DataTable(".data-table")
    </script>
  </body>
</html>

app/views/shared/_ad_table.html.erb
    <tr>
      <td><a href="<%= client_path(ad.client.id) %>"><%= ad.client.name.truncate(30) %></a></td>
      <td><%= ad.width.to_s + " x " + ad.height.to_s %></td>
      <td><%= ad.position.name %></td>
      <td><%= ad.position.platform.name %></td>
      <td><%= ad.rundate.strftime("%d/%m/%y") %></td>
      <td><%= ad.status %></td>
      <td>$<%= ad.price %></td>
      <% if can? :manage, User %>
        <td><%= ad.user.first_name %></td>
      <% end %>

      <td><%= ad.created_at.strftime("%d/%m/%y") %></td>
      <td><%= time_ago_in_words(ad.updated_at) %> ago by <%= get_username_by_id(ad.updated_by) %></td>
    </tr>

app/views/shared/_ad_table_container.html.erb
<table class="table table-hover data-table">
  <thead>
    <tr>
      <th>Client</th>
      <th>W x H (mm)</th>
      <th>Position</th>
      <th>Platform</th>
      <th>Publication date</th>
      <th>Status</th>
      <th>Price</th>
      <% if can? :manage, User %>
        <th>Sales Rep</th>
      <% end %>
      <th>Created</th>
      <th>Updated</th>
    </tr>
  </thead>
  <tbody id="ad-table">
    <%= render partial: "shared/ad_table", collection: ads, as: :ad %>
  </tbody>
</table>

app/views/shared/_nav.html.erb
<div class="collapse" id="navbarToggleExternalContent">
  <div class="bg-dark p-4">
    <h5 class="text-white h4">Collapsed content</h5>
    <span class="text-muted">Toggleable via the navbar brand.</span>
  </div>
</div>
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</nav>

app/views/shared/_sidebar.html.erb
<div class="d-flex flex-column bg-light" style="width: 4.5rem;">
  <a href="/" id="sidebar-home" class="d-block p-3 link-dark text-decoration-none" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Icon-only">
    <%= icon("box", class:"bi") %>
    <span class="visually-hidden">Icon-only</span>
  </a>
  <ul class="nav nav-pills nav-flush flex-column mb-auto text-center">
    <li class="nav-item sidebar-item">
      <a href="#" class="nav-link py-3 border-bottom" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Dashboard">
        <%= icon("speedometer2", class:"bi") %>
      </a>
    </li>
    <li class="nav-item sidebar-item">
      <%= link_to(platforms_path, class: sidebar_class(platforms_path) ) do %>
        <%= icon("newspaper", class:"bi") %>
      <% end %>
    </li>
    <li class="nav-item sidebar-item">
      <!-- <a href="#" class="nav-link py-3 border-bottom" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Clients"> -->
      <%= link_to(clients_path, class: sidebar_class(clients_path) ) do %>
        <%= icon("person-circle", class:"bi") %>
      <% end %>
      <!-- </a> -->
    </li>
    <li class="nav-item sidebar-item">
      <%= link_to(ads_path, class: sidebar_class(ads_path) ) do %>
        <%= icon("card-text", class:"bi") %>
      <% end %>
    </li>
  </ul>
  <div class="dropdown border-top">
    <a href="#" class="d-flex align-items-center justify-content-center p-3 link-dark text-decoration-none dropdown-toggle" id="dropdownUser3" data-bs-toggle="dropdown" aria-expanded="false">
      <img src="https://github.com/mdo.png" alt="mdo" class="rounded-circle" width="24" height="24">
    </a>
    <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser3" style="">
      <li><a class="dropdown-item" href="#">New project...</a></li>
      <li><a class="dropdown-item" href="#">Settings</a></li>
      <li><a class="dropdown-item" href="#">Profile</a></li>
      <li><hr class="dropdown-divider"></li>
      <% if current_user.nil? %>
        <li><%= link_to new_user_session_path, class: 'dropdown-item' do %>Sign in<% end %></li>
      <% else %>
        <li><%= link_to destroy_user_session_path, class: 'dropdown-item', method: :delete do %>Log out<% end %></li>
      <% end %>
    </ul>
  </div>
</div>


<div class="divider"></div>

app/views/shared/_toastr-notifications.html.erb
<% unless flash.empty? %>
   <script type="text/javascript">
      <% flash.each do |f| %>
    <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
   	 toastr['<%= type %>']('<%= f[1] %>');
   <% end %>
   </script>
<% end %>