config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "welcome/index"
  root to: "welcome#index"

  resources :organisations
  resources :clients do
    resources :contacts
  end
  resources :platforms
  resources :positions
  resources :targets
  resources :ads

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.superadmin_role? || user.manager_role?
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/ad.rb
class Ad < ApplicationRecord
  belongs_to :position
  belongs_to :client
  belongs_to :user

  def self.in_publication_range(start_date, end_date)
    where("rundate >= ? AND rundate <= ?", start_date, end_date)
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :organisation
  belongs_to :user

  has_many :contacts
  has_many :ads

end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :client
end

app/models/organisation.rb
class Organisation < ApplicationRecord
  has_many :users
  has_many :clients
  has_many :platforms
end

app/models/platform.rb
class Platform < ApplicationRecord
  belongs_to :organisation
  has_many :positions
  has_many :targets
end

app/models/position.rb
class Position < ApplicationRecord
  belongs_to :platform
  has_many :ads
end

app/models/target.rb
class Target < ApplicationRecord
  belongs_to :platform
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :organisation
  has_many :clients
  has_many :ads
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def index
    if can? :manage, User
      @ads = Ad.all
    else
      @ads = current_user.ads
    end
    @ad = Ad.new
    @clients = Client.all
    @platforms = Platform.all
    @positions = Position.all
  end

  def create
    @ad = Ad.new(ad_params)

    respond_to do |format|
      if @ad.save
        format.html { redirect_to @ad, notice: 'Ad was successfully created.' }
        format.js
        format.json { render json: @ad, status: :created, location: @ad }
      else
        format.html { render action: "error" }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def ad_params
      params.require(:ad).permit(:width, :height, :status, :price, :rundate, :client_id, :position_id, :user_id, :updated_by)
    end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    @clients = Client.all
  end

  def show
    @client = Client.find(params[:id])
    @contacts = Contact.where(client_id: @client.id)
    @ads = @client.ads
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.create(client_params)

    if @client.save
      flash.notice = "Client saved"
      redirect_to clients_path
    else
      flash.now[:error] = "Something went wrong: #{@client.errors.full_messages}"
      render_action :new
    end
  end

  def edit

  end

  def delete

  end

end

private
  def client_params
    params.require(:client).permit(:name, :address, :phone, :website, :organisation_id, :user_id)
  end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.create(contact_params)

    if @contact.save
      flash.notice = "Contact saved"
      redirect_to client_path(params[:client_id])
    else
      flash.now[:error] = "Something went wrong: #{@contact.errors.full_messages}"
      render :new
    end
  end

  def edit

  end

  def destroy
    @contact = Contact.find(params[:id])
    @client = @contact.client
    @contact.destroy

    redirect_to client_path(@client)
  end

  private
    def contact_params
      params.require(:contact).permit(:name, :client_id, :department, :phone, :mobile, :email)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/ads_helper.rb
module AdsHelper

  def publication_end_range(platform_id)
    p = Platform.find(platform_id)
    if p.daily
      return Date.today + 1
    elsif p.weekly
      return Date.today + 1.week
    elsif p.monthly
      return Date.today + 1.month
    end
  end

  def value(collection)
    v = 0
    collection.each do |c|
      v += c.price
    end
    return v
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def get_username_by_id(id)
    u = User.find(id)
    return u.first_name
  end

  def sidebar_class(page)
    if current_page?(page)
      return "nav-link py-3 border-bottom active"
    else
      return "nav-link py-3 border-bottom"
    end
  end

end

app/helpers/bootstrap_icons_helper.rb
module BootstrapIconsHelper
  # refer https://icons.getbootstrap.com/
  def icon(icon, options = {})
    file = File.read("node_modules/bootstrap-icons/icons/#{icon}.svg")
    doc = Nokogiri::HTML::DocumentFragment.parse file
    svg = doc.at_css 'svg'
    if options[:class].present?
      svg['class'] += " " + options[:class]
    end
      doc.to_html.html_safe
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/organisations_helper.rb
module OrganisationsHelper
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/ads/_ad_chart.html.erb
<%= column_chart ads.group_by_week(:rundate, last: 8).count, width: "100%", height: "200px" %>

app/views/ads/error.html.erb
<h2 class="text-white">OH NO!</h2>

app/views/ads/index.html.erb
<section class="py-5 container">

  <div class="card">
    <div class="card-header">
      Bookings
    </div>
    <div class="card-body">
      <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <!-- <button class="btn btn-primary" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasAd" type="submit">Create booking</button> -->
      </div>

      <hr>
      <%= render partial: "ad_chart", locals: {ads: @ads} %>
      <%= render partial: "shared/ad_table_container", locals: {ads: @ads} %>

      <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasAd" aria-labelledby="Positions">
        <div class="offcanvas-header">
          <h3 class="offcanvas-title" id="offcanvasCreateAd">Create Ad</h3>
          <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          <%= form_with( model: @ad, id: "new-ad", local: false ) do |form| %>
            <div class="mb-3">
              <%= form.label :client, class: "form-label" %>
              <%= form.collection_select(:client_id, @clients, :id, :name, {}, {class: "form-select form-control"}) %>
            </div>
            <div class="mb-3">
              <%= form.label :platform, class: "form-label" %>
              <%= form.collection_select(:platform_id, @platforms, :id, :name, {}, {class: "form-select platform-select form-control"}) %>
            </div>
            <div class="mb-3">
              <%= form.label :position, class: "form-label" %>
              <%= form.collection_select(:position_id, @positions, :id, :name, {}, {class: "form-select position-select form-control"}) %>
            </div>
            <div class="mb-3">
              <%= form.label :width, class: "form-label" %>
              <%= form.number_field :width, class: "form-control" %>
            </div>
            <div class="mb-3">
              <%= form.label :height, class: "form-label" %>
              <%= form.number_field :height, class: "form-control" %>
            </div>
            <div class="mb-3">
              <%= form.label :status, class: "form-label" %>
              <%= form.text_field :status, class: "form-control" %>
            </div>
            <div class="mb-3">
              <%= form.label :price, class: "form-label" %>
              <%= form.number_field :price, step: 0.01, class: "form-control" %>
            </div>
            <div class="mb-3">
              <%= form.label :rundate, class: "form-label" %>
              <%= form.date_field :rundate %>
            </div>
            <div class="mb-3">
            <%= form.hidden_field :user_id, value: current_user.id %>
            <%= form.hidden_field :updated_by, value: current_user.id %>
            <%= form.submit :Submit, class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>

    </div>
  </div>


</section>

app/views/clients/_form.html.erb
<%= form_with model: @client do |form| %>
  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.label :address, class: "form-label" %>
    <%= form.text_field :address, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.label :phone, class: "form-label" %>
    <%= form.text_field :phone, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.label :website, class: "form-label" %>
    <%= form.text_field :website, class: "form-control" %>
  </div>
  
  <%= form.hidden_field :user_id, value: current_user.id %>
  <%= form.hidden_field :organisation_id, value: current_user.organisation_id %>
  <%= form.submit :Save, class: "btn btn-primary" %>
<% end %>

app/views/clients/index.html.erb
<section class="py-5 container">

  <div class="card">
    <div class="card-header">
      Clients
    </div>
    <div class="card-body">
      <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <%= link_to('New Client', new_client_url, class: "btn btn-primary") %>
      </div>
      <hr />
      <table class="table table-hover data-table">
        <thead>
          <tr>
            <th scope="col">ID#</th>
            <th scope="col">Client</th>
            <th scope="col">Address</th>
            <th scope="col">Phone</th>
            <th scope="col">Bookings</th>
          </tr>
        </thead>
        <tbody>
          <% @clients.each do |c| %>
            <tr>
              <th scope="row"><%= c.id %></th>
              <td><a href="<%= client_path(c.id) %>"><%= c.name %></a></td>
              <td><%= c.address %></td>
              <td><%= c.phone %></td>
              <td><%= c.ads.count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <% if can? :manage, User %>
	<p>Visible only for superadmins and supervisors! </p>
<% end %>
    </div>
</section>

app/views/clients/new.html.erb
<section class="py-5 container">
  <div class="card">
    <div class="card-header">
      Create Client
    </div>
    <div class="card-body">
      <%= render "form" %>
    </div>
</section>

app/views/clients/show.html.erb
<section class="py-5 container">
  <h2><%= @client.name %></h2>

  <div class="card">
    <div class="card-header">
      Contacts
    </div>
    <div class="card-body">
      <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <%= link_to('Add Contact', new_client_contact_url(@client.id), class: "btn btn-primary") %>
      </div>
      <hr />
      <table class="table">
        <thead>
          <tr>
            <th>Contact</th>
            <th>Department</th>
            <th>Phone</th>
            <th>Mobile</th>
            <th>Email</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody id="ad-table">
          <% @contacts.each do |c| %>
          <tr>
            <td><%= c.name %></td>
            <td><%= c.department %></td>
            <td><%= c.phone %></td>
            <td><%= c.mobile %></td>
            <td><%= c.email %></td>
            <td>
              <div class="dropdown">
                <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                  Actions
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                  <li><%= link_to('Edit', edit_client_contact_url(c.id), class: 'dropdown-item') %></li>
                  <li><%= link_to('Delete', client_contact_path(@client.id, c.id), method: :delete, data: {confirm: 'Are you sure?'}, class: 'dropdown-item') %></li>
                </ul>
              </div>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <br />
  <div class="card">
    <div class="card-header">
      Bookings
    </div>
    <div class="card-body">
      <%= render partial: "shared/ad_table_container", locals: {ads: @ads} %>
    </div>
  </div>
</section>

app/views/contacts/_form.html.erb
<%= form_with model: [:client, @contact] do |form| %>
  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.label :department, class: "form-label" %>
    <%= form.text_field :department, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.label :phone, class: "form-label" %>
    <%= form.text_field :phone, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.label :mobile, class: "form-label" %>
    <%= form.text_field :mobile, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.label :email, class: "form-label" %>
    <%= form.email_field :email, class: "form-control" %>
  </div>

  <%= form.hidden_field :client_id, value: params[:client_id] %>
  <%= form.submit :Save, class: "btn btn-primary" %>
<% end %>

app/views/contacts/new.html.erb
<section class="py-5 container">
  <div class="card">
    <div class="card-header">
      Create Client
    </div>
    <div class="card-body">
      <%= render "form" %>
    </div>
</section>